purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7818177507724613
  brandStrength: 1
  lightness: 0.39209144259803
  brandColors:
    - '#8D9AA3'
    - '#036268'
    - '#55564E'
    - '#D9F8FC'
    - '#4C8C98'
  rhythmicContrast: 0.2070594581309706
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: TAFi
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1397849
layout_spectrum: 0.2526882
