name: TAFi
favicon: null
layout_spectrum: 0.20616867556236684
typography_spectrum: 0.35979462089017034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4451129019726068
  lightness: 0.39209144259802997
  saturation: 0.7818177507724613
  rhythmicContrast: 0.2070594581309706
purpose: []
